# ProjectReportDashboardGenerator

import dataiku
import dataikuapi

from typing import Any, Dict
from abc import ABC
import logging


class ProjectReportDashboardGenerator(ABC):
    """
    Class to create (if not already created), a report DSS dashboard for the project metrics and checks
    """
    check_dataset: dataiku.Dataset = None
    metric_dataset: dataiku.Dataset = None
    project : dataikuapi.dss.project.DSSProject = None
    dashboard : dataikuapi.dss.dashboard.DSSDashboard = None 
    dashboard_name = "Assessement Report"
    page_title = "Project Assessement Tool Report"
    

    def __init__(self,
                 project : dataikuapi.dss.project.DSSProject,
                 check_dataset : dataiku.Dataset, 
                 metric_dataset : dataiku.Dataset):
        """
        Initializes Project Report Dashboard Generator
        """
        self.check_dataset = check_dataset
        self.metric_dataset = metric_dataset
        self.project = project

        
    def generate(self) -> None:
        try:
            self.dashboard = self.get_or_create_dashboard()
            logging.warning(f"Report Dashboard fetch or created successfully")
        except:
            logging.warning(f"Report Dashboard failed to fetch or create")
    
    def get_or_create_dashboard(self) -> dataikuapi.dss.dashboard.DSSDashboard:
        # Load and return dashboard if already exists
        for d in self.project.list_dashboards():
            if d["name"] == self.dashboard_name:
                logging.info(f"Report Dashboard already exists")
                return self.project.get_dashboard(d["id"])
                
        # If dashboard doesn't exist
        logging.info(f"Report Dashboard doesn't exist, creating")
        report_dashboard = self.create_empty_dashboard()
        report_dashboard = self.polulate_dashboard(report_dashboard)
        return report_dashbaord
    
    
    def create_empty_dashboard(self) -> dataikuapi.dss.dashboard.DSSDashboard: 
        # Create an empty single plage dashboard
        logging.info(f"Create empty dashboard")
        dashboard_settings = {   
                                 'pages': [{
                                       "title" : self.page_title,
                                       'grid': {'tiles': []},
                                       'showTitle': True,
                                       'enableCrossFilters': True,
                                       'showFilterPanel': True,
                                       'filtersParams': {'panelPosition': 'TOP', 'engineType': 'LINO'}
                                 }],
                                 'listed': True,
                                 'name': self.dashboard_name,
                                 'showGrid': False,
                                 'showNavigationArrows': False,
                                 'reloadWhenEventReceived': False,
                                 'tags': []
                             }

        return self.project.create_dashboard(self.dashboard_name, settings = dashboard_settings)
    
    def polulate_dashboard(self, report_dashboard : dataikuapi.dss.dashboard.DSSDashboard ) -> dataikuapi.dss.dashboard.DSSDashboard:
        
        # Tile Creation
        logging.info(f"Populating Dashboard's first slide with tiles")
        text_tile = self.create_text_tile()
        
        category_pie_chart_tile = self.create_category_pie_chart_tile(self.create_category_pie_chart_insight())
        
        project_score_tile = self.create_project_score_kpi_tile( self.create_project_score_kpi_chart_insight())
        
        check_dataset_tile = self.create_check_dataset_insight_tile(self.create_check_dataset_table_chart_insight())
        
        line_chart_tile = self.create_line_chart_insight_tile(self.create_line_chart_insight())
        
        settings = report_dashboard.get_settings()
        settings.settings["pages"][0]["grid"]["tiles"] = [text_tile,
                                                          category_pie_chart_tile,
                                                          project_score_tile,
                                                          check_dataset_tile,
                                                          line_chart_tile]
        settings.save()
        return report_dashboard
    
    # Insight creation function
    def create_category_pie_chart_insight(self)-> dataikuapi.dss.insight.DSSInsight:
        name = "Project Score by category"
        category_pie_chart_settings = {
             'type': 'chart',
             'params': {'engineType': 'LINO',
              'refreshableSelection': {'selection': {'useMemTable': False,
                'filter': {'distinct': False, 'enabled': False},
                'partitionSelectionMethod': 'ALL',
                'latestPartitionsN': 1,
                'ordering': {'enabled': False, 'rules': []},
                'samplingMethod': 'HEAD_SEQUENTIAL',
                'maxRecords': 10000,
                'targetRatio': 0.02,
                'ascending': True,
                'withinFirstN': -1,
                'maxReadUncompressedBytes': -1},
               'autoRefreshSample': False,
               '_refreshTrigger': 0},
              'def': {'type': 'pie',
               'variant': 'normal',
               'name': name,
               'userEditedName': True,
               'displayWithEChartsByDefault': True,
               'genericDimension0': [{'column': 'pass',
                 'type': 'ALPHANUM',
                 'numParams': {'emptyBinsMode': 'ZEROS'},
                 'maxValues': 20,
                 'generateOthersCategory': True,
                 'forceLastPositionOthers': False,
                 'oneTickPerBin': False,
                 'filters': [],
                 'isA': 'dimension',
                 'possibleSorts': [{'type': 'NATURAL',
                   'label': 'Natural ordering',
                   'sortAscending': True},
                  {'type': 'AGGREGATION',
                   'measureIdx': 0,
                   'label': 'Count of pass, descending'},
                  {'type': 'AGGREGATION',
                   'measureIdx': 0,
                   'label': 'Count of pass, ascending',
                   'sortAscending': True}],
                 'sort': {'type': 'NATURAL',
                  'label': 'Natural ordering',
                  'sortAscending': True},
                 'prefix': '',
                 'suffix': '',
                 'multiplier': 'Auto',
                 'digitGrouping': 'DEFAULT'}],
               'genericDimension1': [],
               'facetDimension': [{'column': 'check_category',
                 'type': 'ALPHANUM',
                 'numParams': {'emptyBinsMode': 'ZEROS'},
                 'maxValues': 20,
                 'generateOthersCategory': True,
                 'forceLastPositionOthers': False,
                 'oneTickPerBin': False,
                 'filters': [],
                 'isA': 'dimension',
                 'possibleSorts': [{'type': 'NATURAL',
                   'label': 'Natural ordering',
                   'sortAscending': True},
                  {'type': 'AGGREGATION',
                   'measureIdx': 0,
                   'label': 'Count of pass, descending'},
                  {'type': 'AGGREGATION',
                   'measureIdx': 0,
                   'label': 'Count of pass, ascending',
                   'sortAscending': True}],
                 'sort': {'type': 'AGGREGATION',
                  'measureIdx': 0,
                  'label': 'Count of pass, descending'},
                 'prefix': '',
                 'suffix': '',
                 'multiplier': 'Auto',
                 'digitGrouping': 'DEFAULT'}],
               'animationDimension': [],
               'genericMeasures': [{'column': 'pass',
                 'function': 'COUNT',
                 'type': 'ALPHANUM',
                 'displayed': True,
                 'isA': 'measure',
                 'displayAxis': 'axis1',
                 'displayType': 'column',
                 'computeMode': 'NORMAL',
                 'computeModeDim': 0,
                 'multiplier': 'Auto',
                 'digitGrouping': 'DEFAULT',
                 'prefix': '',
                 'suffix': '',
                 'showDisplayLabel': True,
                 'labelPosition': 'BOTTOM',
                 'labelFontSize': 16,
                 'kpiTextAlign': 'CENTER',
                 'kpiValueFontSizeMode': 'RESPONSIVE',
                 'kpiValueFontSize': 32,
                 'colorRules': []}],
               'xDimension': [],
               'yDimension': [],
               'uaXDimension': [],
               'uaYDimension': [],
               'uaDimensionPair': [],
               'uaSize': [],
               'uaColor': [],
               'uaShape': [],
               'uaTooltip': [],
               'groupDimension': [],
               'xMeasure': [],
               'yMeasure': [],
               'colorMeasure': [],
               'sizeMeasure': [],
               'geometry': [],
               'geoLayers': [{'geometry': [],
                 'colorOptions': {'ccScaleMode': 'NORMAL',
                  'paletteType': 'CONTINUOUS',
                  'quantizationMode': 'NONE',
                  'numQuantizeSteps': 5,
                  'paletteMiddleValue': 0.0,
                  'heatDensityMapIntensity': 0.5,
                  'heatDensityMapRadius': 0.5,
                  'singleColor': '#2678B1',
                  'transparency': 0.75,
                  'colorPalette': 'default',
                  'customPalette': {'id': '__dku_custom__',
                   'name': 'Custom Palette',
                   'colors': [],
                   'values': [],
                   'fixedValues': False},
                  'customColors': {}},
                 'uaColor': []}],
               'tooltipMeasures': [],
               'boxplotBreakdownDim': [],
               'boxplotValue': [],
               'filters': [],
               'xAxisFormatting': {'displayAxis': True,
                'showAxisTitle': True,
                'axisTitleFormatting': {'fontSize': 15,
                 'fontColor': '#333',
                 'hasBackground': False},
                'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                  'digitGrouping': 'DEFAULT',
                  'prefix': '',
                  'suffix': ''},
                 'axisTicksFormatting': {'fontSize': 12,
                  'fontColor': '#333',
                  'hasBackground': False}},
                'ticksConfig': {'mode': 'INTERVAL'},
                'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                'isLogScale': False,
                'includeZero': True},
               'yAxesFormatting': [{'id': 'y_left_0',
                 'displayAxis': True,
                 'showAxisTitle': True,
                 'axisTitleFormatting': {'fontSize': 15,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                   'digitGrouping': 'DEFAULT',
                   'prefix': '',
                   'suffix': ''},
                  'axisTicksFormatting': {'fontSize': 12,
                   'fontColor': '#333',
                   'hasBackground': False}},
                 'ticksConfig': {'mode': 'INTERVAL'},
                 'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                 'isLogScale': False,
                 'includeZero': True},
                {'id': 'y_right_0',
                 'displayAxis': True,
                 'showAxisTitle': True,
                 'axisTitleFormatting': {'fontSize': 15,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                   'digitGrouping': 'DEFAULT',
                   'prefix': '',
                   'suffix': ''},
                  'axisTicksFormatting': {'fontSize': 12,
                   'fontColor': '#333',
                   'hasBackground': False}},
                 'ticksConfig': {'mode': 'INTERVAL'},
                 'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                 'isLogScale': False,
                 'includeZero': True}],
               'radialAxisFormatting': {'showAxisTitle': False,
                'axisTitleFormatting': {'fontSize': 15,
                 'fontColor': '#333',
                 'hasBackground': False},
                'ticksConfig': {'mode': 'INTERVAL'},
                'customExtent': {},
                'isLogScale': False,
                'includeZero': True},
               'smoothing': True,
               'showLegend': True,
               'strokeWidth': 2,
               'fillOpacity': 0.6,
               'tooltipOptions': {'display': True},
               'hexbinRadius': 20,
               'hexbinNumber': 20,
               'hexbinRadiusMode': 'NUM_HEXAGONS',
               'valuesInChartDisplayOptions': {'displayValues': False,
                'displayPieLabelsOrValues': False,
                'displayMode': 'LABELS',
                'overlappingStrategy': 'AUTO',
                'textFormatting': {'fontSize': 11,
                 'fontColor': 'AUTO',
                 'hasBackground': False,
                 'backgroundColor': '#D9D9D9BF'}},
               'chartHeight': 200,
               'singleXAxis': True,
               'multiTooltips': False,
               'animationFrameDuration': 3000,
               'animationRepeat': True,
               'colorOptions': {'ccScaleMode': 'NORMAL',
                'paletteType': 'CONTINUOUS',
                'quantizationMode': 'NONE',
                'numQuantizeSteps': 5,
                'paletteMiddleValue': 0.0,
                'heatDensityMapIntensity': 0.5,
                'heatDensityMapRadius': 0.5,
                'singleColor': '#2678B1',
                'transparency': 0.75,
                'colorPalette': 'default',
                'customPalette': {'id': '__dku_custom__',
                 'name': 'Custom Palette',
                 'colors': [],
                 'values': [],
                 'fixedValues': False},
                'customColors': {'v____dku_no_value___': '#c7c7c7',
                 'v_False': '#d62728',
                 'v_True': '#98df8a'}},
               'bubblesOptions': {'defaultRadius': 5.0, 'singleShape': 'FILLED_CIRCLE'},
               'computeMode': 'NORMAL',
               'xAxisMode': 'NORMAL',
               'yAxisMode': 'NORMAL',
               'pieOptions': {'donutHoleSize': 54.0},
               'scatterZoomOptions': {'scale': [1.0, 1.0],
                'translate': [0.0, 0.0],
                'chartWidth': 0.0,
                'enabled': True,
                'persisted': True},
               'linesZoomOptions': {'displayBrush': True,
                'enabled': True,
                'persisted': True},
               'scatterOptions': {'equalScales': False,
                'identityLine': False,
                'connectPoints': {'enabled': False,
                 'lineFormatting': {'color': '#000', 'size': 1}},
                'optimizeRendering': False,
                'regression': {'show': False,
                 'displayFormula': False,
                 'type': 'LINEAR',
                 'labelPosition': 'INSIDE_END',
                 'lineFormatting': {'color': '#000', 'size': 1},
                 'textFormatting': {'fontSize': 11,
                  'fontColor': '#333',
                  'hasBackground': False,
                  'backgroundColor': '#D9D9D9BF'}},
                'numberOfRecords': 1000000.0},
               'scatterMPOptions': {'connectPoints': {'enabled': False,
                 'lineFormatting': {'color': '#000', 'size': 1}},
                'optimizeRendering': False,
                'pairColorOptions': {'singleColor': '#659a88',
                 'transparency': 0.75,
                 'colorPalette': 'default',
                 'customPalette': {'id': '__dku_custom__',
                  'name': 'Custom Palette',
                  'colors': [],
                  'values': [],
                  'fixedValues': False},
                 'customColors': {}},
                'numberOfRecords': 1000000.0},
               'mapOptions': {'tilesLayer': 'cartodb-positron', 'lockSquareGrid': False},
               'mapGridOptions': {'gridLonDeg': 0.6, 'gridLatDeg': 0.6},
               'radarOptions': {'filled': False,
                'polygonsSource': 'MEASURES',
                'lineStyle': {'width': 2.0, 'type': 'SOLID'}},
               'sankeyOptions': {'curveness': 0.5,
                'linkColorVariant': 'GRADIENT',
                'nodeLabelFormatting': {'fontSize': 11,
                 'fontColor': 'AUTO',
                 'hasBackground': False,
                 'backgroundColor': '#D9D9D9BF'}},
               'useLiveProcessingIfAvailable': True,
               'legendPlacement': 'OUTER_RIGHT',
               'legendFormatting': {'fontSize': 11,
                'fontColor': '#333',
                'hasBackground': False},
               'pivotTableOptions': {'displayEmptyValues': False,
                'measureDisplayMode': 'ROWS',
                'displayTotals': {'subTotals': {'rows': True, 'columns': True},
                 'grandTotal': {'row': True, 'column': True}},
                'tableFormatting': {'rowHeaders': {'fontSize': 12,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'columnHeaders': {'fontSize': 12,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'values': {'fontSize': 12, 'fontColor': '#333', 'hasBackground': False}}},
               'gridlinesOptions': {'vertical': {'show': False,
                 'lineFormatting': {'type': 'FILLED', 'color': '#d9d9d9', 'size': 1}},
                'horizontal': {'show': False,
                 'displayAxis': {'type': 'LEFT_Y_AXIS'},
                 'lineFormatting': {'type': 'FILLED', 'color': '#d9d9d9', 'size': 1}}}},
              'customMeasures': [],
              'datasetSmartName': self.check_dataset.get_config().get("name",None)},
             'listed': False,
             'name': name,
             'tags': [],
        }
        pie_chart_insight = self.project.create_insight(category_pie_chart_settings)
        return pie_chart_insight
    
    def create_project_score_kpi_chart_insight(self) -> dataikuapi.dss.insight.DSSInsight:
        name = "Project Score KPI"
        kpi_chart_settings = {
             'type': 'chart',
             'params': {'engineType': 'LINO',
              'refreshableSelection': {'selection': {'useMemTable': False,
                'filter': {'distinct': False, 'enabled': False},
                'partitionSelectionMethod': 'ALL',
                'latestPartitionsN': 1,
                'ordering': {'enabled': False, 'rules': []},
                'samplingMethod': 'HEAD_SEQUENTIAL',
                'maxRecords': 10000,
                'targetRatio': 0.02,
                'ascending': True,
                'withinFirstN': -1,
                'maxReadUncompressedBytes': -1},
               'autoRefreshSample': False,
               '_refreshTrigger': 0},
              'def': {'type': 'kpi',
               'variant': 'normal',
               'name': 'score',
               'userEditedName': False,
               'displayWithEChartsByDefault': True,
               'genericDimension0': [],
               'genericDimension1': [],
               'facetDimension': [],
               'animationDimension': [],
               'genericMeasures': [{'column': 'score',
                 'function': 'CUSTOM',
                 'type': 'CUSTOM',
                 'displayed': True,
                 'isA': 'measure',
                 'displayAxis': 'axis1',
                 'displayType': 'column',
                 'computeMode': 'NORMAL',
                 'computeModeDim': 0,
                 'multiplier': 'Auto',
                 'decimalPlaces': 2,
                 'digitGrouping': 'DEFAULT',
                 'prefix': '',
                 'suffix': '',
                 'showDisplayLabel': True,
                 'labelPosition': 'BOTTOM',
                 'customFunction': 'avg(if(pass, 1, 0))',
                 'inferredType': 'NUMERICAL',
                 'colorRules': [{'mode': 'GREATER_OR_EQUAL_THAN',
                   'value': 0.8,
                   'styleClass': 'color-rule--green-background',
                   'colorOptions': {'ccScaleMode': 'NORMAL',
                    'paletteType': 'CONTINUOUS',
                    'quantizationMode': 'NONE',
                    'numQuantizeSteps': 5,
                    'paletteMiddleValue': 0.0,
                    'heatDensityMapIntensity': 0.5,
                    'heatDensityMapRadius': 0.5,
                    'singleColor': '#659a88',
                    'transparency': 0.75,
                    'colorPalette': 'dku_text_background',
                    'customPalette': {'id': '__dku_custom__',
                     'name': 'Custom palette',
                     'colors': [],
                     'values': [],
                     'fixedValues': False},
                    'customColors': {'customFontColor': '#FFFFFF',
                     'customBackgroundColor': '#668DBB'}}},
                  {'mode': 'GREATER_OR_EQUAL_THAN',
                   'value': 0.5,
                   'styleClass': 'color-rule--orange-background',
                   'colorOptions': {'ccScaleMode': 'NORMAL',
                    'paletteType': 'CONTINUOUS',
                    'quantizationMode': 'NONE',
                    'numQuantizeSteps': 5,
                    'paletteMiddleValue': 0.0,
                    'heatDensityMapIntensity': 0.5,
                    'heatDensityMapRadius': 0.5,
                    'singleColor': '#659a88',
                    'transparency': 0.75,
                    'colorPalette': 'dku_text_background',
                    'customPalette': {'id': '__dku_custom__',
                     'name': 'Custom palette',
                     'colors': [],
                     'values': [],
                     'fixedValues': False},
                    'customColors': {'customFontColor': '#FFFFFF',
                     'customBackgroundColor': '#668DBB'}}},
                  {'mode': 'GREATER_THAN',
                   'value': 0.0,
                   'styleClass': 'color-rule__default',
                   'colorOptions': {'ccScaleMode': 'NORMAL',
                    'paletteType': 'CONTINUOUS',
                    'quantizationMode': 'NONE',
                    'numQuantizeSteps': 5,
                    'paletteMiddleValue': 0.0,
                    'heatDensityMapIntensity': 0.5,
                    'heatDensityMapRadius': 0.5,
                    'singleColor': '#659a88',
                    'transparency': 0.75,
                    'colorPalette': 'dku_text_background',
                    'customPalette': {'id': '__dku_custom__',
                     'name': 'Custom palette',
                     'colors': [],
                     'values': [],
                     'fixedValues': False},
                    'customColors': {'customFontColor': '#FFFFFF',
                     'customBackgroundColor': '#668DBB'}}}]}],
               'xDimension': [],
               'yDimension': [],
               'uaXDimension': [],
               'uaYDimension': [],
               'uaDimensionPair': [],
               'uaSize': [],
               'uaColor': [],
               'uaShape': [],
               'uaTooltip': [],
               'groupDimension': [],
               'xMeasure': [],
               'yMeasure': [],
               'colorMeasure': [],
               'sizeMeasure': [],
               'geometry': [],
               'geoLayers': [{'geometry': [],
                 'colorOptions': {'ccScaleMode': 'NORMAL',
                  'paletteType': 'CONTINUOUS',
                  'quantizationMode': 'NONE',
                  'numQuantizeSteps': 5,
                  'paletteMiddleValue': 0.0,
                  'heatDensityMapIntensity': 0.5,
                  'heatDensityMapRadius': 0.5,
                  'singleColor': '#2678B1',
                  'transparency': 0.75,
                  'colorPalette': 'default',
                  'customPalette': {'id': '__dku_custom__',
                   'name': 'Custom Palette',
                   'colors': [],
                   'values': [],
                   'fixedValues': False},
                  'customColors': {}},
                 'uaColor': []}],
               'tooltipMeasures': [],
               'boxplotBreakdownDim': [],
               'boxplotValue': [],
               'filters': [],
               'xAxisFormatting': {'displayAxis': True,
                'showAxisTitle': True,
                'axisTitleFormatting': {'fontSize': 15,
                 'fontColor': '#333',
                 'hasBackground': False},
                'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                  'digitGrouping': 'DEFAULT',
                  'prefix': '',
                  'suffix': ''},
                 'axisTicksFormatting': {'fontSize': 12,
                  'fontColor': '#333',
                  'hasBackground': False}},
                'ticksConfig': {'mode': 'INTERVAL'},
                'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                'isLogScale': False,
                'includeZero': True},
               'yAxesFormatting': [{'id': 'y_left_0',
                 'displayAxis': True,
                 'showAxisTitle': True,
                 'axisTitleFormatting': {'fontSize': 15,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                   'digitGrouping': 'DEFAULT',
                   'prefix': '',
                   'suffix': ''},
                  'axisTicksFormatting': {'fontSize': 12,
                   'fontColor': '#333',
                   'hasBackground': False}},
                 'ticksConfig': {'mode': 'INTERVAL'},
                 'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                 'isLogScale': False,
                 'includeZero': True},
                {'id': 'y_right_0',
                 'displayAxis': True,
                 'showAxisTitle': True,
                 'axisTitleFormatting': {'fontSize': 15,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                   'digitGrouping': 'DEFAULT',
                   'prefix': '',
                   'suffix': ''},
                  'axisTicksFormatting': {'fontSize': 12,
                   'fontColor': '#333',
                   'hasBackground': False}},
                 'ticksConfig': {'mode': 'INTERVAL'},
                 'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                 'isLogScale': False,
                 'includeZero': True}],
               'radialAxisFormatting': {'showAxisTitle': False,
                'axisTitleFormatting': {'fontSize': 15,
                 'fontColor': '#333',
                 'hasBackground': False},
                'ticksConfig': {'mode': 'INTERVAL'},
                'customExtent': {},
                'isLogScale': False,
                'includeZero': True},
               'smoothing': True,
               'showLegend': True,
               'strokeWidth': 2,
               'fillOpacity': 0.6,
               'tooltipOptions': {'display': True},
               'hexbinRadius': 20,
               'hexbinNumber': 20,
               'hexbinRadiusMode': 'NUM_HEXAGONS',
               'valuesInChartDisplayOptions': {'displayValues': False,
                'displayPieLabelsOrValues': True,
                'displayMode': 'LABELS',
                'overlappingStrategy': 'AUTO',
                'textFormatting': {'fontSize': 11,
                 'fontColor': 'AUTO',
                 'hasBackground': False,
                 'backgroundColor': '#D9D9D9BF'}},
               'chartHeight': 200,
               'singleXAxis': True,
               'multiTooltips': False,
               'animationFrameDuration': 3000,
               'animationRepeat': True,
               'colorOptions': {'ccScaleMode': 'NORMAL',
                'paletteType': 'CONTINUOUS',
                'quantizationMode': 'NONE',
                'numQuantizeSteps': 5,
                'paletteMiddleValue': 0.0,
                'heatDensityMapIntensity': 0.5,
                'heatDensityMapRadius': 0.5,
                'singleColor': '#2678B1',
                'transparency': 0.75,
                'colorPalette': 'default',
                'customPalette': {'id': '__dku_custom__',
                 'name': 'Custom Palette',
                 'colors': [],
                 'values': [],
                 'fixedValues': False},
                'customColors': {}},
               'bubblesOptions': {'defaultRadius': 5.0, 'singleShape': 'FILLED_CIRCLE'},
               'computeMode': 'NORMAL',
               'xAxisMode': 'NORMAL',
               'yAxisMode': 'NORMAL',
               'pieOptions': {'donutHoleSize': 54.0},
               'scatterZoomOptions': {'scale': [1.0, 1.0],
                'translate': [0.0, 0.0],
                'chartWidth': 0.0,
                'enabled': True,
                'persisted': True},
               'linesZoomOptions': {'displayBrush': True,
                'enabled': True,
                'persisted': True},
               'scatterOptions': {'equalScales': False,
                'identityLine': False,
                'regression': {'show': False,
                 'displayFormula': False,
                 'type': 'LINEAR',
                 'labelPosition': 'INSIDE_END',
                 'lineColor': '#000',
                 'lineSize': 1,
                 'textFormatting': {'fontSize': 11,
                  'fontColor': '#333',
                  'hasBackground': False,
                  'backgroundColor': '#D9D9D9BF'}},
                'numberOfRecords': 1000000.0},
               'scatterMPOptions': {'pairColorOptions': {'singleColor': '#659a88',
                 'transparency': 0.75,
                 'colorPalette': 'default',
                 'customPalette': {'id': '__dku_custom__',
                  'name': 'Custom Palette',
                  'colors': [],
                  'values': [],
                  'fixedValues': False},
                 'customColors': {}},
                'numberOfRecords': 1000000.0},
               'mapOptions': {'tilesLayer': 'cartodb-positron', 'lockSquareGrid': False},
               'mapGridOptions': {'gridLonDeg': 0.6, 'gridLatDeg': 0.6},
               'radarOptions': {'filled': False,
                'polygonsSource': 'MEASURES',
                'lineStyle': {'width': 2.0, 'type': 'SOLID'}},
               'sankeyOptions': {'curveness': 0.5,
                'linkColorVariant': 'GRADIENT',
                'nodeLabelFormatting': {'fontSize': 11,
                 'fontColor': 'AUTO',
                 'hasBackground': False,
                 'backgroundColor': '#D9D9D9BF'}},
               'useLiveProcessingIfAvailable': True,
               'legendPlacement': 'OUTER_RIGHT',
               'legendFormatting': {'fontSize': 11,
                'fontColor': '#333',
                'hasBackground': False},
               'pivotTableOptions': {'measureDisplayMode': 'ROWS',
                'displayTotals': {'subTotals': {'rows': True, 'columns': True},
                 'grandTotal': {'row': True, 'column': True}},
                'tableFormatting': {'rowHeaders': {'fontSize': 12,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'columnHeaders': {'fontSize': 12,
                  'fontColor': '#333',
                  'hasBackground': False},
                 'values': {'fontSize': 12,
                  'fontColor': '#333',
                  'hasBackground': False}}}},
              'customMeasures': [{'name': 'score',
                'formula': 'avg(if(pass, 1, 0))',
                'inferredType': 'NUMERICAL'}],
              'datasetSmartName': self.check_dataset.get_config().get("name",None)},
             'listed': False,
             'name': name,
             #'tags': [],
        }
        kpi_chart_insight = self.project.create_insight(kpi_chart_settings)
        return kpi_chart_insight
    
    def create_check_dataset_table_chart_insight(self) -> dataikuapi.dss.insight.DSSInsight:
        name = "Report dataset"
        dataset_chart = {
                 'type': 'dataset_table',
                 'params': {'shakerScript': {'steps': [],
                   'maxProcessedMemTableBytes': -1,
                   'columnsSelection': {'mode': 'ALL'},
                   'columnWidthsByName': {'timestamp': 155,
                    'check_name': 267,
                    'check_category': 120,
                    'project_id': 134,
                    'pass': 100,
                    'message': 300,
                    'result_data': 300},
                   'columnUseScientificNotationByName': {},
                   'coloring': {'scheme': 'INDIVIDUAL_COLUMNS_VALUES',
                    'individualColumns': ['pass'],
                    'individualColumnsRules': [],
                    'valueColoringMode': 'HASH'},
                   'sorting': [{'column': 'timestamp', 'ascending': False}],
                   'analysisColumnData': {},
                   'explorationSampling': {'selection': {'maxRecordsForDisplay': -1,
                     'maxStoredBytes': 104857600,
                     'timeout': -1,
                     'filter': {'distinct': False, 'enabled': False},
                     'partitionSelectionMethod': 'ALL',
                     'latestPartitionsN': 1,
                     'ordering': {'enabled': False, 'rules': []},
                     'samplingMethod': 'HEAD_SEQUENTIAL',
                     'maxRecords': 10000,
                     'targetRatio': 0.02,
                     'ascending': True,
                     'withinFirstN': -1,
                     'maxReadUncompressedBytes': -1},
                    'autoRefreshSample': False,
                    '_refreshTrigger': 1720166828418},
                   'vizSampling': {'selection': {'useMemTable': False,
                     'filter': {'distinct': False, 'enabled': False},
                     'partitionSelectionMethod': 'ALL',
                     'latestPartitionsN': 1,
                     'ordering': {'enabled': False, 'rules': []},
                     'samplingMethod': 'FULL',
                     'maxRecords': -1,
                     'targetRatio': 0.02,
                     'ascending': True,
                     'withinFirstN': -1,
                     'maxReadUncompressedBytes': -1},
                    'autoRefreshSample': False,
                    '_refreshTrigger': 0},
                   'exploreUIParams': {'autoRefresh': True},
                   'globalSearchQuery': '',
                   'explorationFilters': [],
                   'previewMode': 'ALL_ROWS'},
                  'datasetSmartName': self.check_dataset.get_config().get("name",None)},
                 #'owner': 'pierre.petrella',
                 'listed': False,
                 'name': name,
                 'tags': [],
        }

        dataset_chart_insight = self.project.create_insight(dataset_chart)
        return dataset_chart_insight
     
    def create_line_chart_insight(self) -> dataikuapi.dss.insight.DSSInsight:
        name = "Score by category over time"
        line_chart_settings = {
                 'type': 'chart',
                 'params': {'engineType': 'LINO',
                  'refreshableSelection': {'selection': {'useMemTable': False,
                    'filter': {'distinct': False, 'enabled': False},
                    'partitionSelectionMethod': 'ALL',
                    'latestPartitionsN': 1,
                    'ordering': {'enabled': False, 'rules': []},
                    'samplingMethod': 'HEAD_SEQUENTIAL',
                    'maxRecords': 10000,
                    'targetRatio': 0.02,
                    'ascending': True,
                    'withinFirstN': -1,
                    'maxReadUncompressedBytes': -1},
                   'autoRefreshSample': False,
                   '_refreshTrigger': 0},
                  'def': {'type': 'lines',
                   'variant': 'normal',
                   'name': 'score by timestamp and check_category',
                   'userEditedName': True,
                   'displayWithEChartsByDefault': True,
                   'genericDimension0': [{'column': 'timestamp',
                     'type': 'ALPHANUM',
                     'numParams': {'emptyBinsMode': 'ZEROS'},
                     'maxValues': 20,
                     'generateOthersCategory': True,
                     'forceLastPositionOthers': False,
                     'oneTickPerBin': False,
                     'filters': [],
                     'isA': 'dimension',
                     'possibleSorts': [{'type': 'NATURAL',
                       'label': 'Natural ordering',
                       'sortAscending': True},
                      {'type': 'AGGREGATION', 'measureIdx': 0, 'label': 'score, descending'},
                      {'type': 'AGGREGATION',
                       'measureIdx': 0,
                       'label': 'score, ascending',
                       'sortAscending': True},
                      {'type': 'AGGREGATION',
                       'measureIdx': 1,
                       'label': 'Count distinct of check_name, descending'},
                      {'type': 'AGGREGATION',
                       'measureIdx': 1,
                       'label': 'Count distinct of check_name, ascending',
                       'sortAscending': True}],
                     'sort': {'type': 'NATURAL',
                      'label': 'Natural ordering',
                      'sortAscending': True},
                     'prefix': '',
                     'suffix': '',
                     'multiplier': 'Auto',
                     'digitGrouping': 'DEFAULT'}],
                   'genericDimension1': [{'column': 'check_category',
                     'type': 'ALPHANUM',
                     'numParams': {'emptyBinsMode': 'ZEROS'},
                     'maxValues': 20,
                     'generateOthersCategory': True,
                     'forceLastPositionOthers': False,
                     'oneTickPerBin': False,
                     'filters': [],
                     'isA': 'dimension',
                     'possibleSorts': [{'type': 'NATURAL',
                       'label': 'Natural ordering',
                       'sortAscending': True},
                      {'type': 'AGGREGATION', 'measureIdx': 0, 'label': 'score, descending'},
                      {'type': 'AGGREGATION',
                       'measureIdx': 0,
                       'label': 'score, ascending',
                       'sortAscending': True},
                      {'type': 'AGGREGATION',
                       'measureIdx': 1,
                       'label': 'Count distinct of check_name, descending'},
                      {'type': 'AGGREGATION',
                       'measureIdx': 1,
                       'label': 'Count distinct of check_name, ascending',
                       'sortAscending': True}],
                     'sort': {'type': 'AGGREGATION',
                      'measureIdx': 0,
                      'label': 'score, descending'},
                     'prefix': '',
                     'suffix': '',
                     'multiplier': 'Auto',
                     'digitGrouping': 'DEFAULT'}],
                   'facetDimension': [],
                   'animationDimension': [],
                   'genericMeasures': [{'column': 'score',
                     'function': 'CUSTOM',
                     'type': 'CUSTOM',
                     'displayed': True,
                     'isA': 'measure',
                     'displayAxis': 'axis1',
                     'displayType': 'column',
                     'computeMode': 'NORMAL',
                     'computeModeDim': 0,
                     'multiplier': 'Auto',
                     'digitGrouping': 'DEFAULT',
                     'prefix': '',
                     'suffix': '',
                     'showDisplayLabel': True,
                     'labelPosition': 'BOTTOM',
                     'customFunction': 'avg(if(pass, 1, 0))',
                     'inferredType': 'NUMERICAL',
                     'colorRules': []}],
                   'xDimension': [],
                   'yDimension': [],
                   'uaXDimension': [],
                   'uaYDimension': [],
                   'uaDimensionPair': [],
                   'uaSize': [],
                   'uaColor': [],
                   'uaShape': [],
                   'uaTooltip': [],
                   'groupDimension': [],
                   'xMeasure': [],
                   'yMeasure': [],
                   'colorMeasure': [],
                   'sizeMeasure': [],
                   'geometry': [],
                   'geoLayers': [{'geometry': [],
                     'colorOptions': {'ccScaleMode': 'NORMAL',
                      'paletteType': 'CONTINUOUS',
                      'quantizationMode': 'NONE',
                      'numQuantizeSteps': 5,
                      'paletteMiddleValue': 0.0,
                      'heatDensityMapIntensity': 0.5,
                      'heatDensityMapRadius': 0.5,
                      'singleColor': '#2678B1',
                      'transparency': 0.75,
                      'colorPalette': 'default',
                      'customPalette': {'id': '__dku_custom__',
                       'name': 'Custom Palette',
                       'colors': [],
                       'values': [],
                       'fixedValues': False},
                      'customColors': {}},
                     'uaColor': []}],
                   'tooltipMeasures': [{'column': 'check_name',
                     'function': 'COUNTD',
                     'type': 'ALPHANUM',
                     'displayed': True,
                     'isA': 'measure',
                     'displayAxis': 'axis1',
                     'displayType': 'column',
                     'computeModeDim': 0,
                     'multiplier': 'Auto',
                     'digitGrouping': 'DEFAULT',
                     'prefix': '',
                     'suffix': '',
                     'colorRules': []}],
                   'boxplotBreakdownDim': [],
                   'boxplotValue': [],
                   'filters': [],
                   'xAxisFormatting': {'displayAxis': True,
                    'showAxisTitle': True,
                    'axisTitleFormatting': {'fontSize': 15,
                     'fontColor': '#333',
                     'hasBackground': False},
                    'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                      'digitGrouping': 'DEFAULT',
                      'prefix': '',
                      'suffix': ''},
                     'axisTicksFormatting': {'fontSize': 12,
                      'fontColor': '#333',
                      'hasBackground': False}},
                    'ticksConfig': {'mode': 'INTERVAL'},
                    'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                    'isLogScale': False,
                    'includeZero': True},
                   'yAxesFormatting': [{'id': 'y_left_0',
                     'displayAxis': True,
                     'showAxisTitle': True,
                     'axisTitle': 'score by category',
                     'axisTitleFormatting': {'fontSize': 15,
                      'fontColor': '#333',
                      'hasBackground': False},
                     'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                       'digitGrouping': 'DEFAULT'},
                      'axisTicksFormatting': {'fontSize': 12,
                       'fontColor': '#333',
                       'hasBackground': False}},
                     'ticksConfig': {'mode': 'INTERVAL'},
                     'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                     'isLogScale': False,
                     'includeZero': True},
                    {'id': 'y_right_0',
                     'displayAxis': True,
                     'showAxisTitle': True,
                     'axisTitleFormatting': {'fontSize': 15,
                      'fontColor': '#333',
                      'hasBackground': False},
                     'axisValuesFormatting': {'numberFormatting': {'multiplier': 'Auto',
                       'digitGrouping': 'DEFAULT',
                       'prefix': '',
                       'suffix': ''},
                      'axisTicksFormatting': {'fontSize': 12,
                       'fontColor': '#333',
                       'hasBackground': False}},
                     'ticksConfig': {'mode': 'INTERVAL'},
                     'customExtent': {'editMode': 'AUTO', 'manualExtent': [None, None]},
                     'isLogScale': False,
                     'includeZero': True}],
                   'radialAxisFormatting': {'showAxisTitle': False,
                    'axisTitleFormatting': {'fontSize': 15,
                     'fontColor': '#333',
                     'hasBackground': False},
                    'ticksConfig': {'mode': 'INTERVAL'},
                    'customExtent': {},
                    'isLogScale': False,
                    'includeZero': True},
                   'smoothing': True,
                   'showLegend': True,
                   'strokeWidth': 2,
                   'fillOpacity': 0.6,
                   'tooltipOptions': {'display': True},
                   'hexbinRadius': 20,
                   'hexbinNumber': 20,
                   'hexbinRadiusMode': 'NUM_HEXAGONS',
                   'valuesInChartDisplayOptions': {'displayValues': False,
                    'displayPieLabelsOrValues': True,
                    'displayMode': 'LABELS',
                    'overlappingStrategy': 'AUTO',
                    'textFormatting': {'fontSize': 11,
                     'fontColor': 'AUTO',
                     'hasBackground': False,
                     'backgroundColor': '#D9D9D9BF'}},
                   'chartHeight': 200,
                   'singleXAxis': True,
                   'multiTooltips': False,
                   'animationFrameDuration': 3000,
                   'animationRepeat': True,
                   'colorOptions': {'ccScaleMode': 'NORMAL',
                    'paletteType': 'CONTINUOUS',
                    'quantizationMode': 'NONE',
                    'numQuantizeSteps': 5,
                    'paletteMiddleValue': 0.0,
                    'heatDensityMapIntensity': 0.5,
                    'heatDensityMapRadius': 0.5,
                    'singleColor': '#2678B1',
                    'transparency': 0.75,
                    'colorPalette': 'default',
                    'customPalette': {'id': '__dku_custom__',
                     'name': 'Custom Palette',
                     'colors': [],
                     'values': [],
                     'fixedValues': False},
                    'customColors': {}},
                   'bubblesOptions': {'defaultRadius': 5.0, 'singleShape': 'FILLED_CIRCLE'},
                   'computeMode': 'NORMAL',
                   'xAxisMode': 'NORMAL',
                   'yAxisMode': 'NORMAL',
                   'pieOptions': {'donutHoleSize': 54.0},
                   'scatterZoomOptions': {'scale': [1.0, 1.0],
                    'translate': [0.0, 0.0],
                    'chartWidth': 0.0,
                    'enabled': True,
                    'persisted': True},
                   'linesZoomOptions': {'displayBrush': True,
                    'enabled': True,
                    'persisted': True},
                   'scatterOptions': {'equalScales': False,
                    'identityLine': False,
                    'regression': {'show': False,
                     'displayFormula': False,
                     'type': 'LINEAR',
                     'labelPosition': 'INSIDE_END',
                     'lineColor': '#000',
                     'lineSize': 1,
                     'textFormatting': {'fontSize': 11,
                      'fontColor': '#333',
                      'hasBackground': False,
                      'backgroundColor': '#D9D9D9BF'}},
                    'numberOfRecords': 1000000.0},
                   'scatterMPOptions': {'pairColorOptions': {'singleColor': '#659a88',
                     'transparency': 0.75,
                     'colorPalette': 'default',
                     'customPalette': {'id': '__dku_custom__',
                      'name': 'Custom Palette',
                      'colors': [],
                      'values': [],
                      'fixedValues': False},
                     'customColors': {}},
                    'numberOfRecords': 1000000.0},
                   'mapOptions': {'tilesLayer': 'cartodb-positron', 'lockSquareGrid': False},
                   'mapGridOptions': {'gridLonDeg': 0.5, 'gridLatDeg': 0.5},
                   'radarOptions': {'filled': False,
                    'polygonsSource': 'MEASURES',
                    'lineStyle': {'width': 2.0, 'type': 'SOLID'}},
                   'sankeyOptions': {'curveness': 0.5,
                    'linkColorVariant': 'GRADIENT',
                    'nodeLabelFormatting': {'fontSize': 11,
                     'fontColor': 'AUTO',
                     'hasBackground': False,
                     'backgroundColor': '#D9D9D9BF'}},
                   'useLiveProcessingIfAvailable': True,
                   'legendPlacement': 'OUTER_RIGHT',
                   'legendFormatting': {'fontSize': 11,
                    'fontColor': '#333',
                    'hasBackground': False},
                   'pivotTableOptions': {'measureDisplayMode': 'ROWS',
                    'displayTotals': {'subTotals': {'rows': True, 'columns': True},
                     'grandTotal': {'row': True, 'column': True}},
                    'tableFormatting': {'rowHeaders': {'fontSize': 12,
                      'fontColor': '#333',
                      'hasBackground': False},
                     'columnHeaders': {'fontSize': 12,
                      'fontColor': '#333',
                      'hasBackground': False},
                     'values': {'fontSize': 12,
                      'fontColor': '#333',
                      'hasBackground': False}}}},
                  'customMeasures': [{'name': 'score',
                    'formula': 'avg(if(pass, 1, 0))',
                    'inferredType': 'NUMERICAL'}],
                  'datasetSmartName': self.check_dataset.get_config().get("name",None)},
                 'listed': False,
                 'name': name,
                 'tags': [],
        }
        line_chart_insight = self.project.create_insight(line_chart_settings)
        return line_chart_insight
    
    
    # Tile creation function
    def create_text_tile(self) -> dict:
        return {'tileType': 'TEXT',
            'box': {'top': 2, 'left': 10, 'width': 2, 'height': 5},
            'clickAction': 'DO_NOTHING',
            'tileParams': {'text': '#### Project Assessment Tool Logs\n\nFor each run of the **project assessment tool** the results of the checks are appended to a logging dataset.\nThe logging datasets contains:\n- A **timestamp** (of the run time)\n- The **check name** (unique identifier)\n- The **check category** (check themes)\n- The **project ID** (of the checked project)\n- A **pass** flag (true or false)\n- And **result_data** (metadata)',
             'textAlign': 'LEFT',
             'isTransparent': False},
            'autoLoad': True,
            'showTitle': 'NO',
            'displayMode': 'INSIGHT',
            'resizeImageMode': 'FIT_SIZE'}
    
    def create_category_pie_chart_tile(self, insight : dataikuapi.dss.insight.DSSInsight) -> Dict:
        pie_chart_insight_id = insight.insight_id
        return {'tileType': 'INSIGHT',
            'box': {'top': 0, 'left': 0, 'width': 3, 'height': 7},
            'clickAction': 'DO_NOTHING',
            'tileParams': {'showXAxis': True,
             'showYAxis': True,
             'showLegend': False,
             'showBrush': False,
             'inheritLegendPlacement': True,
             'legendPlacement': 'OUTER_RIGHT',
             'showTooltips': True,
             'autoPlayAnimation': True},
            'autoLoad': True,
            'showTitle': 'YES',
            'title': 'Project Scores by Category',
            'insightId': pie_chart_insight_id,
            'insightType': 'chart',
            'displayMode': 'INSIGHT',
            'resizeImageMode': 'FIT_SIZE'}
    
    def create_project_score_kpi_tile (self, insight : dataikuapi.dss.insight.DSSInsight) -> Dict:
        kpi_chart_insight_id = insight.insight_id 
        return {'tileType': 'INSIGHT',
            'box': {'top': 0, 'left': 10, 'width': 2, 'height': 2},
            'clickAction': 'DO_NOTHING',
            'tileParams': {'showXAxis': True,
             'showYAxis': True,
             'showLegend': False,
             'showBrush': False,
             'inheritLegendPlacement': True,
             'legendPlacement': 'OUTER_RIGHT',
             'showTooltips': True,
             'autoPlayAnimation': True},
            'autoLoad': True,
            'showTitle': 'YES',
            'title': 'Project Overall Score',
            'insightId': kpi_chart_insight_id,
            'insightType': 'chart',
            'displayMode': 'INSIGHT',
            'resizeImageMode': 'FIT_SIZE'}

    def create_check_dataset_insight_tile (self, insight : dataikuapi.dss.insight.DSSInsight) -> Dict:
        dataset_insight_id = insight.insight_id
        return {'tileType': 'INSIGHT',
            'box': {'top': 0, 'left': 3, 'width': 7, 'height': 3},
            'clickAction': 'DO_NOTHING',
            'tileParams': {'viewKind': 'EXPLORE',
             'showName': True,
             'showDescription': True,
             'showCustomFields': True,
             'showStorageType': False,
             'showMeaning': False,
             'showProgressBar': False},
            'autoLoad': True,
            'showTitle': 'YES',
            'title': 'Project Check Report Dataset',
            'insightId': dataset_insight_id,
            'insightType': 'dataset_table',
            'displayMode': 'INSIGHT',
            'resizeImageMode': 'FIT_SIZE'}

    def create_line_chart_insight_tile (self, insight : dataikuapi.dss.insight.DSSInsight) -> Dict:
        line_chart_insight_id = insight.insight_id
        
        return {'tileType': 'INSIGHT',
            'box': {'top': 3, 'left': 3, 'width': 7, 'height': 4},
            'clickAction': 'DO_NOTHING',
            'tileParams': {'showXAxis': True,
             'showYAxis': True,
             'showLegend': True,
             'showBrush': False,
             'inheritLegendPlacement': True,
             'legendPlacement': 'OUTER_RIGHT',
             'showTooltips': True,
             'autoPlayAnimation': True},
            'autoLoad': True,
            'showTitle': 'YES',
            'title': 'Project Score by Category over time',
            'insightId': line_chart_insight_id,
            'insightType': 'chart',
            'displayMode': 'INSIGHT',
            'resizeImageMode': 'FIT_SIZE'}
    